force-app/main/default/objects/Order_Dish__c/Order_Dish__c.object-meta.xml
<CustomObject>
    <label>Order Dish</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Dish__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order_Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Dish__c/fields/Dish_Count__c.field-meta.xml
<CustomField>
    <fullName>Dish_Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Dish Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Dish__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Dishes</relationshipLabel>
    <relationshipName>Order_Dishes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Dish__c.Copy_of_Total_Dish_Price__c</summarizedField>
    <summaryForeignKey>Order_Dish__c.Order_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DishOrderController.cls
public with sharing class DishOrderController {
  @AuraEnabled
  public static String makeOrder(Decimal totalPrice) {
    Order_Item__c order = new Order_Item__c(
      Total_Price__c = totalPrice
    );
    insert order;
    return order.Id;
  }

  @AuraEnabled
  public static void addDishToOrder(String orderId, 
                                      String dishId,
                                      String dishComment,
                                      Integer dishCount) {
    Order_Dish__c orderDish = new Order_Dish__c();
    orderDish.Order_Item__c = orderId;
    orderDish.Dish__c = dishId;
    orderDish.Dish_Count__c = dishCount;
    orderDish.Comment__c = dishComment;
    insert orderDish;
  }
}